version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install awscli
  build:
    commands:
      - echo Validating CloudFormation template
      - ./scripts/validate-template.sh
  post_build:
    commands:
      - echo Deploying CloudFormation stack
      - ./scripts/deploy.sh
