Parameters:
  InstanceType:
    Type: String
    Default: "t3.medium"
    Description: "The EC2 instance type"

  DBInstanceType:
    Type: String
    Default: "db.t3.medium"
    Description: "The RDS instance type"
